import { Language } from "./types";

export const translations = {
  en: {
    title: "SinoNexus",
    tagline: "Seamless Success",
    heroTitle: "Your Singapore Pass Eligibility, Instantly Assessed",
    heroSub: "Download our AI-powered app for personalized probability scores and expert guidance.",
    checkNow: "Check Eligibility",
    chatWithNexi: "Chat with Nexi",
    individualServices: "Individual Immigration",
    corporateServices: "Corporate Services",
    individualDesc: "AI-assisted pathway evaluation for professionals and families moving to Singapore.",
    corporateDesc: "End-to-end setup for your business with accounting, payroll, and compliance support.",
    formTitle: "Eligibility Assessment",
    nationality: "Nationality",
    age: "Age",
    salary: "Monthly Salary (SGD)",
    passType: "Pass Type",
    sector: "Industry Sector",
    education: "Highest Education",
    submit: "Get Assessment",
    resultTitle: "Your Approval Probability",
    consultation: "Want personalized guidance to improve your chances?",
    bookConsultation: "Book Expert Consultation",
    corporateLeadTitle: "Let's Connect",
    corporateLeadSub: "Our corporate team specializes in helping businesses navigate Singapore's immigration landscape.",
    companyName: "Company Name",
    contactName: "Your Name",
    email: "Email",
    phone: "Phone",
    requestCallback: "Request Callback"
  },
  zh: {
    title: "SinoNexus",
    tagline: "无缝成功",
    heroTitle: "即刻评估您的新加坡准证申请成功率",
    heroSub: "下载我们的 AI 驱动应用，获取个性化评分和专家指导。",
    checkNow: "检查资格",
    chatWithNexi: "与 Nexi 交谈",
    individualServices: "个人移民服务",
    corporateServices: "企业服务",
    individualDesc: "为移居新加坡的专业人士和家庭提供 AI 辅助的路径评估。",
    corporateDesc: "为您的业务提供会计、薪资和合规支持的端到端设置。",
    formTitle: "资格评估",
    nationality: "国籍",
    age: "年龄",
    salary: "月薪 (新币)",
    passType: "准证类型",
    sector: "行业领域",
    education: "最高学历",
    submit: "获取评估",
    resultTitle: "您的获批概率",
    consultation: "想要个性化指导来提高成功率吗？",
    bookConsultation: "预约专家咨询",
    corporateLeadTitle: "联系我们",
    corporateLeadSub: "我们的企业团队专门帮助企业应对新加坡的移民环境。",
    companyName: "公司名称",
    contactName: "您的姓名",
    email: "电子邮件",
    phone: "电话",
    requestCallback: "请求回访"
  }
};

export const getTranslation = (lang: Language) => translations[lang];
